condense_wildcard_suffixes = true
format_strings = true
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
report_todo = "Always"
report_fixme = "Always"
unstable_features = true
